package jp.muimi.onigame;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.event.ClickEvent;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.*;
import org.bukkit.attribute.Attribute;
import org.bukkit.block.Block;
import org.bukkit.command.*;
import org.bukkit.entity.*;
import org.bukkit.event.*;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.entity.*;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryType;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.BookMeta;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.potion.*;
import org.bukkit.scheduler.BukkitTask;
import org.bukkit.scoreboard.*;
import org.bukkit.util.Vector;

import java.util.*;

public final class OniGamePlugin extends JavaPlugin implements Listener, CommandExecutor, TabCompleter {
    private GameState state=GameState.WAITING;
    private final Set<UUID> participants=new HashSet<>(), players=new HashSet<>(), escaped=new HashSet<>(), dead=new HashSet<>(), playerBots=new HashSet<>(), escapedPlayerBots=new HashSet<>(), deadPlayerBots=new HashSet<>();
    private final Map<UUID,PlayerSkill> selectedSkill=new HashMap<>();
    private final Map<String,Long> cooldowns=new HashMap<>();
    private final Map<String,Integer> heartHp=new HashMap<>();
    private final Map<String,Long> heartAlertAt=new HashMap<>();
    private final Map<UUID,String> repairingHeart=new HashMap<>();
    private final Map<UUID,Long> repairProgressAt=new HashMap<>(), nextSkillCheckAt=new HashMap<>();
    private final Map<UUID,SkillCheck> skillChecks=new HashMap<>();
    private final Map<UUID,String> playerBotWorkingHeart=new HashMap<>();
    private final Map<UUID,Long> nextPlayerBotSkillCheck=new HashMap<>();
    private final Map<UUID,BotSkillCheck> playerBotSkillChecks=new HashMap<>();
    private final Map<UUID,Long> lastSeenAt=new HashMap<>(), heartbeatAt=new HashMap<>();
    private final Map<UUID,Double> stamina=new HashMap<>();
    private final Set<UUID> chased=new HashSet<>();
    private final Map<String,Material> temporaryTestHeartOriginals=new HashMap<>();
    private UUID oni, testParticipant, oniBot; private OniType oniType=OniType.DAKKO, selectedOniType; private int brokenHearts, totalHearts, secondsLeft; private BukkitTask ticker, sidebarTicker, chaseTicker, repairTicker, staminaTicker, botTicker, bgmTicker; private boolean finalPhase, playerSideTest; private String activeBgmSound;
    private Location activeLobby, activeExit, activePlayerSpawn; private long botNextAbilityAt, botRestUntil; private double botStamina=20;
    private NamespacedKey actionKey;
    private record SkillCheck(long startedAt,long targetAt,long endsAt){}
    private record BotSkillCheck(String heartKey,long resolveAt,boolean success){}
    private static final class MenuHolder implements InventoryHolder{private final String type;private Inventory inventory;private MenuHolder(String type){this.type=type;}@Override public Inventory getInventory(){return inventory;}}

    @Override public void onEnable(){saveDefaultConfig(); actionKey=new NamespacedKey(this,"action"); getServer().getPluginManager().registerEvents(this,this); PluginCommand c=getCommand("onigame"); c.setExecutor(this); c.setTabCompleter(this); sidebarTicker=Bukkit.getScheduler().runTaskTimer(this,this::updateSidebars,1,20); chaseTicker=Bukkit.getScheduler().runTaskTimer(this,this::updateHorrorState,5,5);repairTicker=Bukkit.getScheduler().runTaskTimer(this,this::updateHeartRepairs,2,2);staminaTicker=Bukkit.getScheduler().runTaskTimer(this,this::updateStamina,5,5);botTicker=Bukkit.getScheduler().runTaskTimer(this,this::updateBots,10,10);getLogger().info("鬼げぇむ v0.5.4 enabled");}
    @Override public void onDisable(){if(ticker!=null)ticker.cancel();if(sidebarTicker!=null)sidebarTicker.cancel();if(chaseTicker!=null)chaseTicker.cancel();if(repairTicker!=null)repairTicker.cancel();if(staminaTicker!=null)staminaTicker.cancel();if(botTicker!=null)botTicker.cancel();removeOniBot();restoreTemporaryTestHearts();}

    private String cc(String s){return ChatColor.translateAlternateColorCodes('&',s);}
    private void msg(CommandSender s,String m){s.sendMessage(cc("&8[&c鬼げぇむ&8] &f"+m));}
    private void all(String m){Bukkit.broadcastMessage(cc("&8[&c鬼げぇむ&8] &f"+m));}

    @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] a){
        if(a.length==0||a[0].equalsIgnoreCase("help")){help(sender);return true;}
        if(a[0].equalsIgnoreCase("join")&&sender instanceof Player p){if(state!=GameState.WAITING){msg(p,"試合中は参加できません。");return true;} participants.add(p.getUniqueId()); selectedSkill.putIfAbsent(p.getUniqueId(),PlayerSkill.SPRINT);msg(p,"参加しました。現在 &e"+participants.size()+"人");openSkillMenu(p);return true;}
        if(a[0].equalsIgnoreCase("leave")&&sender instanceof Player p){participants.remove(p.getUniqueId());selectedSkill.remove(p.getUniqueId());msg(p,"参加を取り消しました。");return true;}
        if(a[0].equalsIgnoreCase("skill")&&sender instanceof Player p){PlayerSkill sk=a.length>1?PlayerSkill.parse(a[1]):null;if(sk==null){msg(p,"sprint / invisible / smoke / strike から選択してください。");return true;}selectedSkill.put(p.getUniqueId(),sk);msg(p,"スキルを &b"+sk.display+" &fに設定しました。");return true;}
        if(a[0].equalsIgnoreCase("skills")&&sender instanceof Player p){if(state!=GameState.WAITING){msg(p,"スキル選択はロビーで行ってください。");return true;}openSkillMenu(p);return true;}
        if(!sender.hasPermission("onigame.admin")){msg(sender,"権限がありません。");return true;}
        if(a[0].equalsIgnoreCase("gmbook")&&sender instanceof Player p){p.getInventory().addItem(createGmBook());msg(p,"&6GM操作本 &fを渡しました。");return true;}
        if(a[0].equalsIgnoreCase("onimenu")&&sender instanceof Player p){if(state!=GameState.WAITING){msg(p,"鬼選択はロビーで行ってください。");return true;}openOniMenu(p);return true;}
        if(a[0].equalsIgnoreCase("heartmode")&&a.length>1){String mode=a[1].toLowerCase();if(!mode.equals("random")&&!mode.equals("manual")){msg(sender,"random または manual を指定してください。");return true;}getConfig().set("heart-placement-mode",mode);saveConfig();msg(sender,"心臓配置を &e"+(mode.equals("random")?"ランダム":"手動マーカー")+" &fに設定しました。");return true;}
        if(a[0].equalsIgnoreCase("marker")&&sender instanceof Player p){p.getInventory().addItem(createHeartMarker());msg(p,"心臓地点マーカーを渡しました。設置すると自動で透明になります。");return true;}
        if(a[0].equalsIgnoreCase("markers")){int count=scanHeartMarkers(true).size();msg(sender,"有効な心臓地点マーカー: &e"+count+"個");return true;}
        if(a[0].equalsIgnoreCase("bgm")&&a.length>1){if(a[1].equalsIgnoreCase("off")){getConfig().set("final-phase-bgm.enabled",false);saveConfig();stopFinalPhaseBgm();msg(sender,"最終局面BGMを無効にしました。");}else{getConfig().set("final-phase-bgm.enabled",true);getConfig().set("final-phase-bgm.sound",a[1]);saveConfig();msg(sender,"最終局面BGMを &e"+a[1]+" &fに設定しました。");}return true;}
        if(a[0].equalsIgnoreCase("bgmtest")&&sender instanceof Player p){playConfiguredBgm(p);msg(p,"最終局面BGMをテスト再生しました。");return true;}
        if(a[0].equalsIgnoreCase("bgmstop")){stopFinalPhaseBgm();msg(sender,"BGMを停止しました。");return true;}
        if(a[0].equalsIgnoreCase("testbook")&&sender instanceof Player p){if(!isTestGm(p)){msg(p,"この本は参加者0人のテストプレイ中のみ取得できます。");return true;}giveTestPlayBook(p);return true;}
        if(a[0].equalsIgnoreCase("testdestroy")&&sender instanceof Player p){if(!isTestGm(p)){msg(p,"この操作は参加者0人のテストプレイ中のみ使用できます。");return true;}Block target=p.getTargetBlockExact(getConfig().getInt("test-heart-target-range",20));if(target==null||!heartHp.containsKey(LocationStore.encode(target.getLocation()))){msg(p,"視線の先に未破壊の心臓がありません。");return true;}destroyHeart(target);msg(p,"視線先の心臓をテスト操作で破壊しました。");return true;}
        if(a[0].equalsIgnoreCase("botgame")&&sender instanceof Player p){OniType type=a.length>1?OniType.parse(a[1]):selectedOniType;if(type==null)type=OniType.DAKKO;start(type,p,true);return true;}
        if(a[0].equalsIgnoreCase("onibotgame")&&sender instanceof Player p){OniType type=a.length>1?OniType.parse(a[1]):selectedOniType;if(type==null)type=OniType.DAKKO;int count=3;if(a.length>2)try{count=Integer.parseInt(a[2]);}catch(NumberFormatException ignored){}startOniVsBots(type,p,Math.max(1,Math.min(8,count)));return true;}
        if(a[0].equalsIgnoreCase("set")&&sender instanceof Player p&&a.length>1){
            switch(a[1].toLowerCase()){
                case "lobby" -> LocationStore.set(getConfig(),"locations.lobby",p.getLocation());
                case "player" -> LocationStore.set(getConfig(),"locations.player-spawn",p.getLocation());
                case "oni" -> LocationStore.set(getConfig(),"locations.oni-spawn",p.getLocation());
                case "exit" -> LocationStore.set(getConfig(),"locations.exit",p.getLocation());
                default -> {msg(p,"lobby / player / oni / exit を指定してください。");return true;}
            } saveConfig();msg(p,a[1]+"地点を設定しました。");return true;
        }
        if(a[0].equalsIgnoreCase("heart")&&sender instanceof Player p){List<String> list=getConfig().getStringList("locations.hearts");String encoded=LocationStore.encode(p.getLocation());if(list.contains(encoded)){list.remove(encoded);msg(p,"この心臓候補を削除しました。");}else{list.add(encoded);msg(p,"心臓候補を追加しました（"+list.size()+"件）。");}getConfig().set("locations.hearts",list);saveConfig();return true;}
        if(a[0].equalsIgnoreCase("start")){OniType type=a.length>1?OniType.parse(a[1]):null;start(type,sender,false);return true;}
        if(a[0].equalsIgnoreCase("stop")){end(false,"管理者が試合を終了しました");return true;}
        if(a[0].equalsIgnoreCase("status")){String mode=getConfig().getString("heart-placement-mode","random");msg(sender,"状態: "+state+" / 参加: "+participants.size()+" / ぷれいやーBot: "+playerBots.size()+" / 心臓: "+brokenHearts+"/"+totalHearts+" / 配置: "+mode+" / 選択鬼: "+(selectedOniType==null?"ランダム":selectedOniType.display));return true;}
        help(sender);return true;
    }
    private void help(CommandSender s){s.sendMessage(cc("&c&l鬼げぇむ &7- commands\n&e/onigame join|leave / skills &7参加・スキルUI\n&e/onigame skill <sprint|invisible|smoke|strike>\n&e/onigame gmbook / onimenu &7GM本・鬼選択UI\n&e/onigame heartmode <random|manual>\n&e/onigame marker / markers &7手動配置マーカー\n&e/onigame bgm <sound|off> / bgmtest / bgmstop\n&e/onigame botgame [dakko|kishin] &7ぷれいやー対鬼Bot\n&e/onigame onibotgame [dakko|kishin] [1-8] &7鬼対ぷれいやーBot\n&e/onigame testbook / testdestroy &7[ソロテスト専用]\n&e/onigame set <lobby|player|oni|exit> &7[管理]\n&e/onigame heart &7ランダム候補を追加/削除\n&e/onigame start [dakko|kishin] / stop / status"));}

    private void start(OniType forced,CommandSender starter,boolean playerTest){
        if(state!=GameState.WAITING){all("すでに試合中です。");return;}
        participants.removeIf(id->Bukkit.getPlayer(id)==null);
        boolean soloTest=participants.isEmpty();
        if(soloTest){if(!(starter instanceof Player gm)){msg(starter,"参加者0人のテスト開始はゲーム内のGMが実行してください。");return;}testParticipant=gm.getUniqueId();participants.add(testParticipant);msg(gm,playerTest?"&eGMをぷれいやー、NPCを鬼にしたBotテストを開始します。":"&e参加者0人のため、GMを鬼にしたテストモードで開始します。");}
        else if(!playerTest&&participants.size()<getConfig().getInt("minimum-players",2)){all("参加人数が足りません。0人テストまたは必要人数以上で開始してください。");return;}
        Player testGm=soloTest?Bukkit.getPlayer(testParticipant):null;
        Location ps=LocationStore.get(getConfig(),"locations.player-spawn"), os=LocationStore.get(getConfig(),"locations.oni-spawn"), ex=LocationStore.get(getConfig(),"locations.exit"), lobby=LocationStore.get(getConfig(),"locations.lobby");
        String placementMode=getConfig().getString("heart-placement-mode","random");
        List<Location> hearts=placementMode.equalsIgnoreCase("manual")?scanHeartMarkers(true):selectRandomHearts();
        boolean automaticTestHearts=soloTest&&hearts.isEmpty();
        if(soloTest&&testGm!=null){Location base=testGm.getLocation().clone();if(ps==null)ps=base.clone();if(os==null)os=playerTest?base.clone().add(horizontalDirection(base).multiply(12)):base.clone();if(lobby==null)lobby=base.clone();if(ex==null)ex=base.clone().subtract(horizontalDirection(base).multiply(8));if(automaticTestHearts)hearts=createAutomaticTestHearts(base);msg(testGm,"&aテスト用地点を自動補完しました。未設定のロビー・開始地点・出口・心臓は現在地周辺を使用します。");}
        if(ps==null||os==null||ex==null||hearts.isEmpty()){all("開始地点・鬼地点・出口・現在の配置方式に対応する心臓地点を設定してください。");if(testParticipant!=null){participants.remove(testParticipant);testParticipant=null;}return;}
        resetRuntime(); List<UUID> ids=new ArrayList<>(participants); Collections.shuffle(ids);playerSideTest=playerTest;oniType=forced!=null?forced:(selectedOniType!=null?selectedOniType:OniType.values()[new Random().nextInt(2)]);if(playerTest){oni=null;players.addAll(ids);}else{oni=ids.remove(0);players.addAll(ids);}
        activeLobby=lobby;activeExit=ex;activePlayerSpawn=ps;
        Material heartMat=Material.matchMaterial(getConfig().getString("heart-material","CRYING_OBSIDIAN")); if(heartMat==null)heartMat=Material.CRYING_OBSIDIAN;
        for(Location l:hearts){if(automaticTestHearts)temporaryTestHeartOriginals.put(LocationStore.encode(l),l.getBlock().getType());l.getBlock().setType(heartMat);heartHp.put(LocationStore.encode(l),getConfig().getInt("heart-max-health",100));}
        totalHearts=heartHp.size();secondsLeft=getConfig().getInt("game-seconds",1200);state=GameState.RUNNING;
        String oniName;if(playerTest){LivingEntity bot=spawnOniBot(os);oniName="鬼Bot";for(UUID id:players)setupPlayer(Bukkit.getPlayer(id),ps);if(soloTest)giveTestPlayBook(testGm);}else{Player op=Bukkit.getPlayer(oni);setupOni(op,os);for(UUID id:players)setupPlayer(Bukkit.getPlayer(id),ps);if(soloTest)giveTestPlayBook(op);oniName=op.getName();}
        all("&4&l鬼げぇむ 開始！ &f鬼は &c"+oniName+" &7(&c"+oniType.display+"&7) &fです。心臓を破壊し、討伐または脱出せよ。");
        ticker=Bukkit.getScheduler().runTaskTimer(this,this::tick,20,20);
    }
    private void startOniVsBots(OniType type,Player gm,int count){if(!participants.isEmpty()){msg(gm,"鬼対ぷれいやーBot戦は参加者0人の状態で開始してください。");return;}start(type,gm,false);if(state!=GameState.RUNNING||oni==null||!oni.equals(gm.getUniqueId()))return;for(int i=0;i<count;i++)spawnPlayerBot(activePlayerSpawn,i+1);all("&bぷれいやーBot "+count+"体 &fが心臓の破壊を開始した……");}
    private void resetRuntime(){stopFinalPhaseBgm();removeOniBot();removePlayerBots();restoreTemporaryTestHearts();players.clear();escaped.clear();dead.clear();chased.clear();lastSeenAt.clear();heartbeatAt.clear();stamina.clear();repairingHeart.clear();repairProgressAt.clear();nextSkillCheckAt.clear();skillChecks.clear();playerBotWorkingHeart.clear();nextPlayerBotSkillCheck.clear();playerBotSkillChecks.clear();heartAlertAt.clear();cooldowns.clear();heartHp.clear();brokenHearts=0;finalPhase=false;playerSideTest=false;botStamina=20;botRestUntil=0;if(ticker!=null)ticker.cancel();}
    private void common(Player p){p.getInventory().clear();p.getActivePotionEffects().forEach(e->p.removePotionEffect(e.getType()));p.setGameMode(GameMode.ADVENTURE);p.setWalkSpeed((float)getConfig().getDouble("player-walk-speed",0.20));p.setHealth(20);p.setFoodLevel(20);p.setFireTicks(0);}
    private void setupPlayer(Player p,Location at){common(p);p.teleport(at);PlayerSkill sk=selectedSkill.getOrDefault(p.getUniqueId(),PlayerSkill.SPRINT);p.getInventory().setItem(0,item(skillMaterial(sk),"&b&l"+sk.display,"skill:"+sk.name()));p.getInventory().setItem(8,item(Material.COMPASS,"&d心臓探知機","tracker"));}
    private void setupOni(Player p,Location at){common(p);p.teleport(at);p.setWalkSpeed((float)getConfig().getDouble("oni-walk-speed",0.24));p.getAttribute(Attribute.GENERIC_MAX_HEALTH).setBaseValue(60);p.setHealth(60);p.addPotionEffect(new PotionEffect(PotionEffectType.INCREASE_DAMAGE,Integer.MAX_VALUE,0,false,false));p.getInventory().setItem(0,item(Material.NETHERITE_SWORD,"&4&l鬼の爪","oni_weapon"));if(oniType==OniType.DAKKO){equipDakkoArmor(p);p.getInventory().setItem(1,item(Material.ENDER_PEARL,"&d狐渡り","dakko_tp"));p.getInventory().setItem(2,item(Material.FOX_SPAWN_EGG,"&6分霊","dakko_clone"));}else{p.getInventory().setItem(1,item(Material.FIREWORK_ROCKET,"&c鬼突","kishin_charge"));p.getInventory().setItem(2,item(Material.IRON_AXE,"&4地砕","kishin_slam"));}}
    private LivingEntity spawnOniBot(Location at){Zombie bot=at.getWorld().spawn(at,Zombie.class);bot.setBaby(false);bot.setCustomName(cc("&4鬼Bot「"+oniType.display+"」"));bot.setCustomNameVisible(false);bot.setPersistent(true);bot.setRemoveWhenFarAway(false);bot.setCanPickupItems(false);bot.addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY,Integer.MAX_VALUE,0,false,false));bot.getAttribute(Attribute.GENERIC_MAX_HEALTH).setBaseValue(60);bot.setHealth(60);bot.getAttribute(Attribute.GENERIC_MOVEMENT_SPEED).setBaseValue(getConfig().getDouble("bot.movement-speed",0.32));bot.getAttribute(Attribute.GENERIC_ATTACK_DAMAGE).setBaseValue(getConfig().getDouble("bot.attack-damage",7.0));bot.getEquipment().setItemInMainHand(new ItemStack(Material.NETHERITE_SWORD));bot.getEquipment().setItemInMainHandDropChance(0);if(oniType==OniType.DAKKO){bot.getEquipment().setHelmet(oniArmor(Material.CHAINMAIL_HELMET,"&5堕狐の面"));bot.getEquipment().setChestplate(oniArmor(Material.CHAINMAIL_CHESTPLATE,"&5堕狐の装束"));bot.getEquipment().setLeggings(oniArmor(Material.CHAINMAIL_LEGGINGS,"&5堕狐の袴"));bot.getEquipment().setBoots(oniArmor(Material.CHAINMAIL_BOOTS,"&5堕狐の足袋"));}bot.getEquipment().setHelmetDropChance(0);bot.getEquipment().setChestplateDropChance(0);bot.getEquipment().setLeggingsDropChance(0);bot.getEquipment().setBootsDropChance(0);oniBot=bot.getUniqueId();botNextAbilityAt=System.currentTimeMillis()+5000;return bot;}
    private LivingEntity getOniEntity(){if(oniBot!=null&&Bukkit.getEntity(oniBot) instanceof LivingEntity entity)return entity;return oni==null?null:Bukkit.getPlayer(oni);}
    private void removeOniBot(){if(oniBot!=null){Entity entity=Bukkit.getEntity(oniBot);if(entity!=null)entity.remove();oniBot=null;}}
    private LivingEntity spawnPlayerBot(Location origin,int number){Location at=origin.clone().add((number-1)%3-1,0,(number-1)/3);Zombie bot=at.getWorld().spawn(at,Zombie.class);bot.setBaby(false);bot.setAI(false);bot.setSilent(true);bot.setCustomName("ぷれいやーBot "+number);bot.setCustomNameVisible(false);bot.setPersistent(true);bot.setRemoveWhenFarAway(false);bot.addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY,Integer.MAX_VALUE,0,false,false));bot.getAttribute(Attribute.GENERIC_MAX_HEALTH).setBaseValue(20);bot.setHealth(20);bot.getEquipment().setHelmet(plainBotArmor(Material.LEATHER_HELMET));bot.getEquipment().setChestplate(plainBotArmor(Material.LEATHER_CHESTPLATE));bot.getEquipment().setLeggings(plainBotArmor(Material.LEATHER_LEGGINGS));bot.getEquipment().setBoots(plainBotArmor(Material.LEATHER_BOOTS));bot.getEquipment().setItemInMainHand(new ItemStack(Material.IRON_PICKAXE));bot.getEquipment().setHelmetDropChance(0);bot.getEquipment().setChestplateDropChance(0);bot.getEquipment().setLeggingsDropChance(0);bot.getEquipment().setBootsDropChance(0);bot.getEquipment().setItemInMainHandDropChance(0);playerBots.add(bot.getUniqueId());return bot;}
    private ItemStack plainBotArmor(Material material){ItemStack item=new ItemStack(material);ItemMeta meta=item.getItemMeta();meta.setUnbreakable(true);item.setItemMeta(meta);return item;}
    private void removePlayerBots(){for(UUID id:new HashSet<>(playerBots)){Entity entity=Bukkit.getEntity(id);if(entity!=null)entity.remove();}playerBots.clear();escapedPlayerBots.clear();deadPlayerBots.clear();}
    private Material skillMaterial(PlayerSkill s){return switch(s){case SPRINT->Material.FEATHER;case INVISIBLE->Material.GLASS_BOTTLE;case SMOKE->Material.INK_SAC;case ONI_STRIKE->Material.BLAZE_ROD;};}
    private ItemStack item(Material m,String name,String action){ItemStack i=new ItemStack(m);ItemMeta im=i.getItemMeta();im.setDisplayName(cc(name));im.getPersistentDataContainer().set(actionKey,PersistentDataType.STRING,action);i.setItemMeta(im);return i;}
    private ItemStack menuItem(Material material,String name,String action,String... lore){ItemStack i=item(material,name,action);ItemMeta m=i.getItemMeta();m.setLore(Arrays.stream(lore).map(this::cc).toList());i.setItemMeta(m);return i;}
    private ItemStack customModelItem(Material material,int model,String name,String action,String... lore){ItemStack i=menuItem(material,name,action,lore);ItemMeta m=i.getItemMeta();m.setCustomModelData(model);i.setItemMeta(m);return i;}
    private void openSkillMenu(Player p){MenuHolder holder=new MenuHolder("skills");Inventory menu=Bukkit.createInventory(holder,27,cc("&4鬼げぇむ &8- &0スキル選択"));holder.inventory=menu;PlayerSkill current=selectedSkill.getOrDefault(p.getUniqueId(),PlayerSkill.SPRINT);menu.setItem(10,menuItem(Material.FEATHER,"&b&l疾走","menu_skill:SPRINT","&7効果: 5秒間高速移動","&7クールダウン: 25秒",current==PlayerSkill.SPRINT?"&a現在選択中":"&eクリックして選択"));menu.setItem(12,menuItem(Material.GLASS_BOTTLE,"&f&l隠形","menu_skill:INVISIBLE","&7効果: 6秒間透明化","&7クールダウン: 40秒",current==PlayerSkill.INVISIBLE?"&a現在選択中":"&eクリックして選択"));menu.setItem(14,menuItem(Material.INK_SAC,"&8&l煙幕","menu_skill:SMOKE","&7効果: 鬼の視界を妨害","&7クールダウン: 35秒",current==PlayerSkill.SMOKE?"&a現在選択中":"&eクリックして選択"));menu.setItem(16,menuItem(Material.BLAZE_ROD,"&c&l破鬼撃","menu_skill:ONI_STRIKE","&7効果: 鬼を怯ませて距離を作る","&7クールダウン: 45秒",current==PlayerSkill.ONI_STRIKE?"&a現在選択中":"&eクリックして選択"));p.openInventory(menu);}
    private void openOniMenu(Player p){MenuHolder holder=new MenuHolder("oni");Inventory menu=Bukkit.createInventory(holder,27,cc("&4鬼げぇむ &8- &0鬼選択"));holder.inventory=menu;menu.setItem(11,customModelItem(Material.CHAINMAIL_HELMET,1001,"&5&l堕狐","menu_oni:DAKKO","&7奇襲・攪乱型","&d狐渡り &7/ &6分霊",selectedOniType==OniType.DAKKO?"&a現在選択中":"&eクリックして選択"));menu.setItem(15,menuItem(Material.NETHERITE_AXE,"&4&l鬼神","menu_oni:KISHIN","&7正面突破・追跡型","&c鬼突 &7/ &4地砕",selectedOniType==OniType.KISHIN?"&a現在選択中":"&eクリックして選択"));p.openInventory(menu);}
    private ItemStack createHeartMarker(){ItemStack i=item(Material.ARMOR_STAND,"&4&l鬼の心臓地点マーカー","heart_marker");ItemMeta m=i.getItemMeta();m.setLore(List.of(cc("&7設置地点に心臓を生成します。"),cc("&7設置後は透明・固定・無敵になります。")));i.setItemMeta(m);return i;}
    private void equipDakkoArmor(Player p){
        p.getInventory().setHelmet(oniArmor(Material.CHAINMAIL_HELMET,"&5堕狐の面"));
        p.getInventory().setChestplate(oniArmor(Material.CHAINMAIL_CHESTPLATE,"&5堕狐の装束"));
        p.getInventory().setLeggings(oniArmor(Material.CHAINMAIL_LEGGINGS,"&5堕狐の袴"));
        p.getInventory().setBoots(oniArmor(Material.CHAINMAIL_BOOTS,"&5堕狐の足袋"));
    }
    private ItemStack oniArmor(Material material,String name){ItemStack i=item(material,name,"dakko_armor");ItemMeta m=i.getItemMeta();m.setUnbreakable(true);m.setCustomModelData(dakkoArmorModel(material));m.setLore(List.of(cc("&8堕狐専用装備")));i.setItemMeta(m);return i;}
    private int dakkoArmorModel(Material material){return switch(material){case CHAINMAIL_HELMET->1001;case CHAINMAIL_CHESTPLATE->1002;case CHAINMAIL_LEGGINGS->1003;case CHAINMAIL_BOOTS->1004;default->1001;};}
    private boolean isDakkoArmor(ItemStack i){if(i==null||!i.hasItemMeta())return false;return "dakko_armor".equals(i.getItemMeta().getPersistentDataContainer().get(actionKey,PersistentDataType.STRING));}
    private boolean isTestGm(Player p){return state==GameState.RUNNING&&testParticipant!=null&&testParticipant.equals(p.getUniqueId());}
    private void giveTestPlayBook(Player p){p.getInventory().setItem(8,createTestPlayBook());msg(p,"&eテストプレイ本 &fをホットバーへ配布しました。");}
    private ItemStack createGmBook(){
        ItemStack book=new ItemStack(Material.WRITTEN_BOOK);BookMeta m=(BookMeta)book.getItemMeta();
        m.title(Component.text("鬼げぇむ GM操作本",NamedTextColor.DARK_RED));m.author(Component.text("鬼げぇむ"));
        Component page1=Component.text("【心臓の配置方式】\n\n",NamedTextColor.DARK_RED)
                .append(button("▶ ランダム配置\n",NamedTextColor.GREEN,"/og heartmode random"))
                .append(Component.text("登録候補から設定個数を抽選\n\n",NamedTextColor.GRAY))
                .append(button("▶ 手動配置\n",NamedTextColor.GOLD,"/og heartmode manual"))
                .append(Component.text("専用マーカーの全地点に生成",NamedTextColor.GRAY));
        Component page2=Component.text("【心臓マーカー】\n\n",NamedTextColor.DARK_RED)
                .append(button("▶ マーカーを受け取る\n",NamedTextColor.GOLD,"/og marker"))
                .append(button("▶ マーカー数を確認\n",NamedTextColor.AQUA,"/og markers"))
                .append(Component.text("\n設置したマーカーは自動で透明になります。",NamedTextColor.GRAY));
        Component page3=Component.text("【ゲーム操作】\n\n",NamedTextColor.DARK_RED)
                .append(button("▶ 鬼を選択\n",NamedTextColor.GOLD,"/og onimenu"))
                .append(button("▶ 選択した鬼で開始\n",NamedTextColor.RED,"/og start"))
                .append(button("▶ 状態を確認\n",NamedTextColor.AQUA,"/og status"))
                .append(button("▶ ゲームを停止",NamedTextColor.DARK_RED,"/og stop"));
        Component page4=Component.text("【ぷれいやーBotテスト】\n\n",NamedTextColor.DARK_RED)
                .append(Component.text("GMがぷれいやーになり、鬼Botと対戦します。\n\n",NamedTextColor.GRAY))
                .append(button("▶ 堕狐Bot戦を開始\n",NamedTextColor.LIGHT_PURPLE,"/og botgame dakko"))
                .append(button("▶ 鬼神Bot戦を開始",NamedTextColor.RED,"/og botgame kishin"));
        Component page5=Component.text("【鬼対ぷれいやーBot】\n\n",NamedTextColor.DARK_RED)
                .append(Component.text("GMが鬼になり、革装備のぷれいやーBot 3体と対戦します。\n\n",NamedTextColor.GRAY))
                .append(button("▶ 堕狐で開始\n",NamedTextColor.LIGHT_PURPLE,"/og onibotgame dakko 3"))
                .append(button("▶ 鬼神で開始",NamedTextColor.RED,"/og onibotgame kishin 3"));
        m.pages(List.of(page1,page2,page3,page4,page5));book.setItemMeta(m);return book;
    }
    private ItemStack createTestPlayBook(){ItemStack book=new ItemStack(Material.WRITTEN_BOOK);BookMeta m=(BookMeta)book.getItemMeta();m.title(Component.text("鬼げぇむ テストプレイ",NamedTextColor.GOLD));m.author(Component.text("鬼げぇむ"));Component page1=Component.text("【心臓テスト】\n\n",NamedTextColor.DARK_RED).append(Component.text("破壊したい心臓へ視点を合わせて押してください。\n\n",NamedTextColor.GRAY)).append(button("▶ 視線先の心臓を破壊\n",NamedTextColor.RED,"/og testdestroy")).append(button("▶ 現在状態を確認",NamedTextColor.AQUA,"/og status"));Component page2=Component.text("【BGMテスト】\n\n",NamedTextColor.DARK_PURPLE).append(button("▶ 最終局面BGMを再生\n",NamedTextColor.GREEN,"/og bgmtest")).append(button("▶ BGMを停止",NamedTextColor.RED,"/og bgmstop"));Component page3=Component.text(playerSideTest?"【鬼Botテスト】\n\n":"【鬼スキル確認】\n\n",NamedTextColor.DARK_RED).append(Component.text(playerSideTest?"あなたはぷれいやーです。\n鬼Botの心音・発見・追跡・攻撃・脱出を確認できます。":"堕狐\n2: 狐渡り\n3: 分霊\n\n鬼神\n2: 鬼突\n3: 地砕\n\n各アイテムを右クリック",NamedTextColor.GRAY));Component page4=Component.text("【テスト終了】\n\n",NamedTextColor.DARK_RED).append(Component.text("装備・速度・BGM・一時参加状態を解除してロビーへ戻ります。\n\n",NamedTextColor.GRAY)).append(button("▶ テストプレイを終了",NamedTextColor.RED,"/og stop"));m.pages(List.of(page1,page2,page3,page4));book.setItemMeta(m);return book;}
    private Component button(String text,NamedTextColor color,String command){return Component.text(text,color).clickEvent(ClickEvent.runCommand(command));}
    private List<Location> selectRandomHearts(){List<Location> locations=new ArrayList<>(getConfig().getStringList("locations.hearts").stream().map(LocationStore::decode).filter(Objects::nonNull).toList());Collections.shuffle(locations);int count=Math.min(Math.max(1,getConfig().getInt("random-heart-count",5)),locations.size());return new ArrayList<>(locations.subList(0,count));}
    private List<Location> scanHeartMarkers(boolean hide){
        String markerName=getConfig().getString("heart-marker-name","鬼の心臓地点");Map<String,Location> unique=new LinkedHashMap<>();
        for(World world:Bukkit.getWorlds())for(ArmorStand stand:world.getEntitiesByClass(ArmorStand.class))if(markerName.equals(stand.getCustomName())){if(hide)configureMarker(stand);Location l=stand.getLocation().getBlock().getLocation();unique.put(LocationStore.encode(l),l);}
        return new ArrayList<>(unique.values());
    }
    private Vector horizontalDirection(Location base){Vector direction=base.getDirection().setY(0);return direction.lengthSquared()<0.01?new Vector(0,0,1):direction.normalize();}
    private List<Location> createAutomaticTestHearts(Location base){Vector forward=horizontalDirection(base),right=new Vector(-forward.getZ(),0,forward.getX());List<Location> result=new ArrayList<>();for(int side=-1;side<=1;side++){Location candidate=base.clone().add(forward.clone().multiply(5)).add(right.clone().multiply(side*3));candidate.setX(Math.floor(candidate.getX()));candidate.setZ(Math.floor(candidate.getZ()));candidate.setY(base.getBlockY()+1);while(candidate.getBlockY()<candidate.getWorld().getMaxHeight()-1&&!candidate.getBlock().isEmpty())candidate.add(0,1,0);if(candidate.getBlock().isEmpty())result.add(candidate.getBlock().getLocation());}return result;}
    private void restoreTemporaryTestHearts(){for(Map.Entry<String,Material> entry:new HashMap<>(temporaryTestHeartOriginals).entrySet()){Location location=LocationStore.decode(entry.getKey());if(location!=null)location.getBlock().setType(entry.getValue());}temporaryTestHeartOriginals.clear();}
    private void configureMarker(ArmorStand stand){stand.setCustomName(getConfig().getString("heart-marker-name","鬼の心臓地点"));stand.setCustomNameVisible(false);stand.setVisible(false);stand.setGravity(false);stand.setInvulnerable(true);stand.setMarker(true);stand.setPersistent(true);}

    private void tick(){if(state!=GameState.RUNNING)return;secondsLeft--;for(UUID id:participants){Player p=Bukkit.getPlayer(id);if(p==null)continue;String warning=chased.contains(id)?"  &7|  &4&l追跡中":"";p.sendActionBar(cc("&c心臓 "+brokenHearts+"/&f"+totalHearts+"  &7|  &e残り "+(secondsLeft/60)+":"+String.format("%02d",secondsLeft%60)+warning));}checkExit();if(secondsLeft<=0)end(true,"時間切れ――鬼の勝利");}
    private void updateStamina(){if(state!=GameState.RUNNING)return;double drain=getConfig().getDouble("stamina.drain-per-second",2.0)/4.0,recovery=getConfig().getDouble("stamina.recovery-per-second",1.5)/4.0,sneakRecovery=getConfig().getDouble("stamina.sneak-recovery-per-second",2.5)/4.0;for(UUID id:participants){Player p=Bukkit.getPlayer(id);if(p==null||p.getGameMode()==GameMode.SPECTATOR)continue;double value=stamina.getOrDefault(id,20.0);if(p.isSprinting()&&p.getVelocity().setY(0).lengthSquared()>0.005)value-=drain;else value+=p.isSneaking()?sneakRecovery:recovery;value=Math.max(0,Math.min(20,value));stamina.put(id,value);p.setFoodLevel((int)Math.ceil(value));p.setSaturation(0);if(value<=0&&p.isSprinting()){p.setSprinting(false);p.sendActionBar(cc("&cスタミナ切れ &7――歩くか、止まって回復"));}}LivingEntity hunter=getOniEntity();if(hunter!=null&&brokenHearts<totalHearts){double heal=getConfig().getDouble("oni-heart-protection.regeneration-per-second",1.0)/4.0;hunter.setHealth(Math.min(hunter.getAttribute(Attribute.GENERIC_MAX_HEALTH).getValue(),hunter.getHealth()+heal));}}
    private void updateBots(){updateOniBot();updatePlayerBots();}
    private void updateOniBot(){if(state!=GameState.RUNNING||oniBot==null)return;if(!(Bukkit.getEntity(oniBot) instanceof Mob bot))return;long now=System.currentTimeMillis();Player target=players.stream().filter(id->!dead.contains(id)&&!escaped.contains(id)).map(Bukkit::getPlayer).filter(Objects::nonNull).filter(p->p.getWorld().equals(bot.getWorld())).min(Comparator.comparingDouble(p->p.getLocation().distanceSquared(bot.getLocation()))).orElse(null);if(target==null){bot.setTarget(null);return;}if(now<botRestUntil){bot.setTarget(null);botStamina=Math.min(20,botStamina+getConfig().getDouble("stamina.sneak-recovery-per-second",2.5)/2.0);return;}bot.setTarget(target);double distance=bot.getLocation().distance(target.getLocation());if(distance>2.2)botStamina-=getConfig().getDouble("stamina.drain-per-second",2.0)/2.0;else botStamina=Math.min(20,botStamina+getConfig().getDouble("stamina.recovery-per-second",1.5)/2.0);if(botStamina<=0){botStamina=0;botRestUntil=now+(long)(getConfig().getDouble("bot.rest-seconds",3.0)*1000);bot.getWorld().playSound(bot.getLocation(),Sound.ENTITY_RAVAGER_STUNNED,0.6f,1.2f);return;}if(now<botNextAbilityAt)return;if(oniType==OniType.DAKKO&&brokenHearts<4&&distance>8&&distance<24){Location behind=target.getLocation().clone().subtract(horizontalDirection(target.getLocation()).multiply(3));behind.setY(target.getLocation().getY());bot.teleport(behind);bot.getWorld().spawnParticle(Particle.SOUL_FIRE_FLAME,bot.getLocation(),30,0.5,1,0.5,0.04);botNextAbilityAt=now+(long)((20+brokenHearts*3)*1000L);}else if(oniType==OniType.KISHIN&&distance>5&&distance<16){Vector charge=target.getLocation().toVector().subtract(bot.getLocation().toVector()).normalize().multiply(Math.max(1.2,2.1-brokenHearts*.15)).setY(.15);bot.setVelocity(charge);bot.getWorld().playSound(bot.getLocation(),Sound.ENTITY_RAVAGER_ROAR,1,1);botNextAbilityAt=now+(long)((18+brokenHearts*3)*1000L);}}
    private void updatePlayerBots(){if(state!=GameState.RUNNING||playerBots.isEmpty())return;LivingEntity hunter=getOniEntity();for(UUID id:new HashSet<>(playerBots)){if(deadPlayerBots.contains(id)||escapedPlayerBots.contains(id))continue;if(!(Bukkit.getEntity(id) instanceof LivingEntity bot)){deadPlayerBots.add(id);continue;}Location destination=null;boolean fleeing=false;if(hunter!=null&&hunter.getWorld().equals(bot.getWorld())&&hunter.getLocation().distanceSquared(bot.getLocation())<Math.pow(getConfig().getDouble("player-bot.flee-radius",10.0),2)){clearPlayerBotWork(id);Vector away=bot.getLocation().toVector().subtract(hunter.getLocation().toVector()).setY(0);if(away.lengthSquared()<0.01)away=new Vector(1,0,0);destination=bot.getLocation().clone().add(away.normalize().multiply(8));fleeing=true;}else if(brokenHearts>=totalHearts){clearPlayerBotWork(id);destination=activeExit;}else destination=heartHp.keySet().stream().map(LocationStore::decode).filter(Objects::nonNull).filter(l->l.getWorld().equals(bot.getWorld())).min(Comparator.comparingDouble(l->l.distanceSquared(bot.getLocation()))).orElse(null);if(destination==null)continue;double distance=bot.getLocation().distance(destination);if(!fleeing&&brokenHearts<totalHearts&&distance<=2.6){advanceHeartBot(id,bot,destination.getBlock());continue;}if(!fleeing)clearPlayerBotWork(id);if(brokenHearts>=totalHearts&&distance<=getConfig().getDouble("exit-radius",3.0)){escapedPlayerBots.add(id);bot.remove();all("&bぷれいやーBot &fが脱出しました！");checkPlayerOutcome();continue;}movePlayerBot(bot,destination,fleeing?getConfig().getDouble("player-bot.flee-step",0.85):getConfig().getDouble("player-bot.move-step",0.65));}}
    private void movePlayerBot(LivingEntity bot,Location destination,double step){Vector direction=destination.toVector().subtract(bot.getLocation().toVector()).setY(0);if(direction.lengthSquared()<0.01)return;direction.normalize();Location next=bot.getLocation().clone().add(direction.clone().multiply(step));next.setDirection(direction);if(next.getBlock().isPassable()&&next.clone().add(0,1,0).getBlock().isPassable())bot.teleport(next);else{Location raised=next.clone().add(0,1,0);if(raised.getBlock().isPassable()&&raised.clone().add(0,1,0).getBlock().isPassable())bot.teleport(raised);}}
    private void advanceHeartBot(UUID botId,LivingEntity bot,Block block){String key=LocationStore.encode(block.getLocation());if(!heartHp.containsKey(key))return;long now=System.currentTimeMillis();bot.swingMainHand();if(!key.equals(playerBotWorkingHeart.get(botId))){playerBotWorkingHeart.put(botId,key);scheduleNextPlayerBotSkillCheck(botId,now);playerBotSkillChecks.remove(botId);}BotSkillCheck check=playerBotSkillChecks.get(botId);if(check!=null&&now>=check.resolveAt()){playerBotSkillChecks.remove(botId);if(check.success()){heartHp.computeIfPresent(key,(k,hp)->Math.max(0,hp-Math.max(0,getConfig().getInt("skill-check-success-bonus",3))));bot.getWorld().playSound(bot.getLocation(),Sound.ENTITY_EXPERIENCE_ORB_PICKUP,0.7f,1.5f);bot.getWorld().spawnParticle(Particle.VILLAGER_HAPPY,bot.getLocation().add(0,1,0),5,0.3,0.4,0.3,0.02);}else{int max=getConfig().getInt("heart-max-health",100);heartHp.computeIfPresent(key,(k,hp)->Math.min(max,hp+Math.max(0,getConfig().getInt("skill-check-failure-penalty",8))));forceHeartAlert(block.getLocation());bot.getWorld().playSound(bot.getLocation(),Sound.ENTITY_GENERIC_EXPLODE,1.0f,0.75f);bot.getWorld().spawnParticle(Particle.EXPLOSION_LARGE,block.getLocation().add(.5,.5,.5),1);}scheduleNextPlayerBotSkillCheck(botId,now);}else if(check==null&&now>=nextPlayerBotSkillCheck.getOrDefault(botId,Long.MAX_VALUE)){boolean success=Math.random()<getConfig().getDouble("player-bot.skill-check-success-chance",0.78);long reaction=(long)(getConfig().getDouble("player-bot.skill-check-reaction-seconds",0.65)*1000);playerBotSkillChecks.put(botId,new BotSkillCheck(key,now+reaction,success));bot.getWorld().playSound(bot.getLocation(),Sound.BLOCK_NOTE_BLOCK_PLING,0.7f,1.4f);bot.getWorld().spawnParticle(Particle.ELECTRIC_SPARK,bot.getLocation().add(0,1.4,0),6,0.2,0.2,0.2,0.02);}heartHp.computeIfPresent(key,(k,hp)->Math.max(0,hp-Math.max(1,getConfig().getInt("heart-progress-per-interval",1))));int hp=heartHp.getOrDefault(key,0);updateHeartCracks(block,hp);notifyHeartAttack(block.getLocation(),key,now);if(hp<=0)destroyHeart(block);}
    private void scheduleNextPlayerBotSkillCheck(UUID id,long now){long min=(long)(getConfig().getDouble("skill-check-min-seconds",4.0)*1000),max=(long)(getConfig().getDouble("skill-check-max-seconds",9.0)*1000);nextPlayerBotSkillCheck.put(id,now+min+(long)(Math.random()*Math.max(1,max-min)));}
    private void clearPlayerBotWork(UUID id){playerBotWorkingHeart.remove(id);nextPlayerBotSkillCheck.remove(id);playerBotSkillChecks.remove(id);}
    private void updateHorrorState(){
        if(state!=GameState.RUNNING)return;LivingEntity hunter=getOniEntity();if(hunter==null)return;long now=System.currentTimeMillis();
        double terror=getConfig().getDouble("oni-terror-radius",28.0), detect=getConfig().getDouble("oni-detection-range",24.0), fov=getConfig().getDouble("oni-field-of-view",110.0);
        long lostMillis=(long)(getConfig().getDouble("chase-lost-seconds",8.0)*1000L);
        for(UUID id:players){
            if(dead.contains(id)||escaped.contains(id))continue;Player target=Bukkit.getPlayer(id);if(target==null)continue;
            double distance=target.getWorld().equals(hunter.getWorld())?target.getLocation().distance(hunter.getLocation()):Double.MAX_VALUE;
            if(distance<=terror)playHeartbeat(target,distance,terror,now);
            boolean visible=distance<=detect&&hunter.hasLineOfSight(target)&&isInOniView(hunter,target,fov);
            if(visible){lastSeenAt.put(id,now);if(chased.add(id))beginChase(hunter,target);}
            else if(chased.contains(id)&&now-lastSeenAt.getOrDefault(id,now)>lostMillis){chased.remove(id);target.sendTitle(cc("&7追跡から逃れた"),cc("&8息を潜めろ……"),5,30,10);target.playSound(target.getLocation(),Sound.BLOCK_AMETHYST_BLOCK_RESONATE,0.5f,0.6f);}
        }
    }
    private boolean isInOniView(LivingEntity hunter,Player target,double fov){if(hunter.getLocation().distanceSquared(target.getLocation())<=9)return true;Vector direction=hunter.getEyeLocation().getDirection().normalize();Vector toward=target.getEyeLocation().toVector().subtract(hunter.getEyeLocation().toVector()).normalize();return direction.dot(toward)>=Math.cos(Math.toRadians(fov/2.0));}
    private void beginChase(LivingEntity hunter,Player target){target.sendTitle(cc("&4&l見つかった"),cc("&c逃げろ"),5,35,10);target.addPotionEffect(new PotionEffect(PotionEffectType.DARKNESS,35,0,false,false));target.playSound(target.getLocation(),Sound.BLOCK_SCULK_SHRIEKER_SHRIEK,1.0f,1.0f);if(hunter instanceof Player p)p.sendActionBar(cc("&4獲物を発見: &f"+target.getName()));hunter.getWorld().playSound(hunter.getLocation(),Sound.ENTITY_WARDEN_ANGRY,0.5f,1.2f);}
    private void playHeartbeat(Player target,double distance,double terror,long now){double ratio=Math.max(0,Math.min(1,distance/terror));long interval=(long)(350+ratio*1200);if(now-heartbeatAt.getOrDefault(target.getUniqueId(),0L)<interval)return;heartbeatAt.put(target.getUniqueId(),now);float volume=(float)(0.35+(1-ratio)*0.9);float pitch=(float)(0.65+(1-ratio)*0.45);target.playSound(target.getLocation(),Sound.ENTITY_WARDEN_HEARTBEAT,volume,pitch);}
    private void updateSidebars(){if(state==GameState.RUNNING||state==GameState.ENDING)updateGameSidebar();else updateLobbySidebar();}
    private void updateLobbySidebar(){
        for(Player viewer:Bukkit.getOnlinePlayers()){
            Scoreboard board=Bukkit.getScoreboardManager().getNewScoreboard();
            Objective o=board.registerNewObjective("onigame","dummy",cc("&4&l-鬼げぇむ-"));o.setDisplaySlot(DisplaySlot.SIDEBAR);
            o.getScore(cc("&7──────────")).setScore(3);
            o.getScore(cc("&fオンライン数")).setScore(2);
            o.getScore(cc("&a"+Bukkit.getOnlinePlayers().size()+" &7人")).setScore(1);
            viewer.setScoreboard(board);
        }
    }
    private void updateGameSidebar(){
        Scoreboard board=Bukkit.getScoreboardManager().getNewScoreboard();
        Objective o=board.registerNewObjective("onigame","dummy",cc("&4&l-鬼げぇむ-"));o.setDisplaySlot(DisplaySlot.SIDEBAR);
        int score=15;
        o.getScore(cc("&e残り時間 &f"+(Math.max(0,secondsLeft)/60)+":"+String.format("%02d",Math.max(0,secondsLeft)%60))).setScore(score--);
        o.getScore(cc("&c心臓 &f"+brokenHearts+"&7/&f"+totalHearts)).setScore(score--);
        o.getScore(cc("&8──────────")).setScore(score--);
        List<UUID> shown=new ArrayList<>(players);shown.sort(Comparator.comparing(id->{Player p=Bukkit.getPlayer(id);return p==null?"":p.getName();}));
        for(UUID id:shown){
            if(score<=0)break;
            Player target=Bukkit.getPlayer(id);String name=target!=null?target.getName():"退出者";String icon;
            if(escaped.contains(id))icon="&f◆";
            else if(dead.contains(id)||target==null)icon="&c✖";
            else {double max=Objects.requireNonNull(target.getAttribute(Attribute.GENERIC_MAX_HEALTH)).getValue();icon=target.getHealth()<=max*.30?"&e▲":"&a●";}
            o.getScore(cc(icon+" &f"+trimName(name))).setScore(score--);
        }
        int botNumber=1;for(UUID id:playerBots){if(score<=0)break;String icon=escapedPlayerBots.contains(id)?"&f◆":deadPlayerBots.contains(id)||Bukkit.getEntity(id)==null?"&c✖":"&a●";o.getScore(cc(icon+" &fBot "+botNumber++)).setScore(score--);}
        if(score>0)o.getScore(cc("&8──────────&0")).setScore(score--);
        if(score>0)o.getScore(cc("&a● 通常  &e▲ 瀕死")).setScore(score--);
        if(score>0)o.getScore(cc("&c✖ 脱落  &f◆ 脱出")).setScore(score);
        for(Player viewer:Bukkit.getOnlinePlayers())viewer.setScoreboard(board);
    }
    private String trimName(String name){return name.length()>12?name.substring(0,12):name;}
    private void checkExit(){if(brokenHearts<totalHearts)return;Location exit=activeExit!=null?activeExit:LocationStore.get(getConfig(),"locations.exit");if(exit==null)return;for(UUID id:new HashSet<>(players)){if(dead.contains(id)||escaped.contains(id))continue;Player p=Bukkit.getPlayer(id);if(p!=null&&p.getWorld().equals(exit.getWorld())&&p.getLocation().distanceSquared(exit)<=Math.pow(getConfig().getDouble("exit-radius",3),2)){escaped.add(id);p.setGameMode(GameMode.SPECTATOR);all("&b"+p.getName()+" &fが脱出しました！");}}checkPlayerOutcome();}
    private void checkPlayerOutcome(){if(state!=GameState.RUNNING)return;long active=players.stream().filter(id->!dead.contains(id)&&!escaped.contains(id)).count()+playerBots.stream().filter(id->!deadPlayerBots.contains(id)&&!escapedPlayerBots.contains(id)).count();if(active==0){if(!escaped.isEmpty()||!escapedPlayerBots.isEmpty())end(false,"&b生 還――ぷれいやーの勝利");else end(true,"&4全 滅――鬼の勝利");}}
    private void end(boolean oniWin,String reason){if(state==GameState.WAITING)return;state=GameState.ENDING;if(ticker!=null)ticker.cancel();stopFinalPhaseBgm();all((oniWin?"&4&l":"&b&l")+reason);Bukkit.getScheduler().runTaskLater(this,()->{Location lobby=activeLobby!=null?activeLobby:LocationStore.get(getConfig(),"locations.lobby");restoreTemporaryTestHearts();for(UUID id:participants){Player p=Bukkit.getPlayer(id);if(p==null)continue;p.getAttribute(Attribute.GENERIC_MAX_HEALTH).setBaseValue(20);common(p);if(lobby!=null)p.teleport(lobby);}if(testParticipant!=null){participants.remove(testParticipant);selectedSkill.remove(testParticipant);testParticipant=null;}activeLobby=null;activeExit=null;activePlayerSpawn=null;state=GameState.WAITING;resetRuntime();},100);}

    @EventHandler public void onBreak(BlockBreakEvent e){if(state==GameState.RUNNING&&heartHp.containsKey(LocationStore.encode(e.getBlock().getLocation())))e.setCancelled(true);}
    private void toggleHeartRepair(Player player,Block block){String key=LocationStore.encode(block.getLocation());if(!heartHp.containsKey(key)||!players.contains(player.getUniqueId())||dead.contains(player.getUniqueId())||escaped.contains(player.getUniqueId()))return;if(key.equals(repairingHeart.get(player.getUniqueId()))){stopRepair(player,"&7心臓への干渉を中断した。 ");return;}repairingHeart.put(player.getUniqueId(),key);long now=System.currentTimeMillis();repairProgressAt.put(player.getUniqueId(),now);scheduleNextSkillCheck(player.getUniqueId(),now);skillChecks.remove(player.getUniqueId());player.sendActionBar(cc("&4心臓への干渉を開始 &7――離れると中断"));player.playSound(player.getLocation(),Sound.BLOCK_RESPAWN_ANCHOR_CHARGE,0.7f,0.65f);}
    private void stopRepair(Player player,String message){UUID id=player.getUniqueId();repairingHeart.remove(id);repairProgressAt.remove(id);nextSkillCheckAt.remove(id);skillChecks.remove(id);if(message!=null)player.sendActionBar(cc(message));}
    private void scheduleNextSkillCheck(UUID id,long now){long min=(long)(getConfig().getDouble("skill-check-min-seconds",4.0)*1000),max=(long)(getConfig().getDouble("skill-check-max-seconds",9.0)*1000);nextSkillCheckAt.put(id,now+min+(long)(Math.random()*Math.max(1,max-min)));}
    private void updateHeartRepairs(){
        if(state!=GameState.RUNNING)return;long now=System.currentTimeMillis();
        for(Map.Entry<UUID,String> entry:new HashMap<>(repairingHeart).entrySet()){
            Player player=Bukkit.getPlayer(entry.getKey());Location location=LocationStore.decode(entry.getValue());
            if(player==null||location==null||!heartHp.containsKey(entry.getValue())||dead.contains(entry.getKey())||escaped.contains(entry.getKey())||!player.getWorld().equals(location.getWorld())||player.getLocation().distanceSquared(location.clone().add(.5,.5,.5))>12.25){if(player!=null)stopRepair(player,"&7心臓から離れたため作業を中断した。");continue;}
            SkillCheck check=skillChecks.get(entry.getKey());
            if(check!=null){if(now>check.endsAt()){failSkillCheck(player,location,entry.getValue(),"時間切れ");continue;}showSkillCheck(player,check,now);}
            else if(now>=nextSkillCheckAt.getOrDefault(entry.getKey(),Long.MAX_VALUE)){startSkillCheck(player,now);continue;}
            long interval=getConfig().getLong("heart-progress-interval-ticks",10)*50L;if(now-repairProgressAt.getOrDefault(entry.getKey(),0L)>=interval){repairProgressAt.put(entry.getKey(),now);advanceHeart(player,location.getBlock(),Math.max(1,getConfig().getInt("heart-progress-per-interval",1)));}
        }
    }
    private void startSkillCheck(Player player,long now){long duration=(long)(getConfig().getDouble("skill-check-duration-seconds",2.4)*1000);long target=now+(long)(duration*(0.45+Math.random()*0.30));skillChecks.put(player.getUniqueId(),new SkillCheck(now,target,now+duration));player.playSound(player.getLocation(),Sound.BLOCK_NOTE_BLOCK_PLING,0.8f,1.4f);player.sendTitle("",cc("&e&lスキルチェック！ &fSHIFT"),0,15,0);}
    private void showSkillCheck(Player player,SkillCheck check,long now){int length=15,cursor=Math.min(length-1,(int)(((now-check.startedAt())/(double)(check.endsAt()-check.startedAt()))*length)),target=Math.min(length-1,(int)(((check.targetAt()-check.startedAt())/(double)(check.endsAt()-check.startedAt()))*length));StringBuilder bar=new StringBuilder("&8[");for(int i=0;i<length;i++){if(i==cursor)bar.append("&f◆");else if(Math.abs(i-target)<=1)bar.append("&a▰");else bar.append("&7▱");}bar.append("&8] &eSHIFT");player.sendActionBar(cc(bar.toString()));}
    private void resolveSkillCheck(Player player){SkillCheck check=skillChecks.get(player.getUniqueId());if(check==null)return;long now=System.currentTimeMillis(),window=(long)(getConfig().getDouble("skill-check-success-window-seconds",0.40)*1000);Location heart=LocationStore.decode(repairingHeart.get(player.getUniqueId()));if(heart==null)return;if(Math.abs(now-check.targetAt())<=window){skillChecks.remove(player.getUniqueId());scheduleNextSkillCheck(player.getUniqueId(),now);advanceHeart(player,heart.getBlock(),Math.max(0,getConfig().getInt("skill-check-success-bonus",3)));player.sendTitle("",cc("&a&l成功"),0,15,5);player.playSound(player.getLocation(),Sound.ENTITY_EXPERIENCE_ORB_PICKUP,0.8f,1.5f);}else failSkillCheck(player,heart,LocationStore.encode(heart),"タイミング失敗");}
    private void failSkillCheck(Player player,Location heart,String heartKey,String reason){skillChecks.remove(player.getUniqueId());scheduleNextSkillCheck(player.getUniqueId(),System.currentTimeMillis());int max=getConfig().getInt("heart-max-health",100),penalty=Math.max(0,getConfig().getInt("skill-check-failure-penalty",8));heartHp.computeIfPresent(heartKey,(k,hp)->Math.min(max,hp+penalty));updateHeartCracks(heart.getBlock(),heartHp.getOrDefault(heartKey,max));player.sendTitle(cc("&4&l失敗"),cc("&c"+reason),0,25,8);heart.getWorld().playSound(heart,Sound.ENTITY_GENERIC_EXPLODE,1.2f,0.7f);heart.getWorld().spawnParticle(Particle.EXPLOSION_LARGE,heart.clone().add(.5,.5,.5),2);forceHeartAlert(heart);}
    private void advanceHeart(Player player,Block block,int amount){String key=LocationStore.encode(block.getLocation());if(!heartHp.containsKey(key))return;int hp=Math.max(0,heartHp.get(key)-amount);heartHp.put(key,hp);updateHeartCracks(block,hp);block.getWorld().spawnParticle(Particle.DAMAGE_INDICATOR,block.getLocation().add(.5,.6,.5),2,0.25,0.25,0.25,0.02);int max=getConfig().getInt("heart-max-health",100),percent=(int)Math.round((1-hp/(double)Math.max(1,max))*100);if(!skillChecks.containsKey(player.getUniqueId()))player.sendActionBar(cc("&4心臓損傷 &c"+percent+"% &7――作業中"));notifyHeartAttack(block.getLocation(),key,System.currentTimeMillis());if(hp<=0)destroyHeart(block);}
    private void destroyHeart(Block block){String key=LocationStore.encode(block.getLocation());if(!heartHp.containsKey(key))return;for(UUID id:new HashSet<>(repairingHeart.keySet()))if(key.equals(repairingHeart.get(id))){Player p=Bukkit.getPlayer(id);if(p!=null)stopRepair(p,null);}heartHp.remove(key);for(Player viewer:block.getWorld().getPlayers())viewer.sendBlockDamage(block.getLocation(),0f);block.setType(Material.AIR);brokenHearts++;all("&c鬼の心臓が破壊された！ &f("+brokenHearts+"/"+totalHearts+")");block.getWorld().playSound(block.getLocation(),Sound.ENTITY_WITHER_DEATH,0.7f,0.55f);weakenOni();if(brokenHearts==totalHearts){all("&4鬼の不死性が消滅した。脱出口が開いた！");startFinalPhaseBgm();}}
    private void updateHeartCracks(Block block,int hp){int max=getConfig().getInt("heart-max-health",100);float progress=Math.max(0f,Math.min(1f,1f-hp/(float)Math.max(1,max)));for(Player viewer:block.getWorld().getPlayers())viewer.sendBlockDamage(block.getLocation(),progress);}
    private void notifyHeartAttack(Location heart,String heartKey,long now){long cooldown=(long)(getConfig().getDouble("heart-alert-cooldown-seconds",5.0)*1000L);if(now-heartAlertAt.getOrDefault(heartKey,0L)<cooldown)return;heartAlertAt.put(heartKey,now);LivingEntity hunter=getOniEntity();if(hunter==null)return;if(hunter instanceof Player p)msg(p,"&4心臓が傷つけられている…… &c"+directionFrom(p.getLocation(),heart));hunter.getWorld().playSound(hunter.getLocation(),Sound.ENTITY_WARDEN_HEARTBEAT,1.0f,0.55f);}
    private void forceHeartAlert(Location heart){LivingEntity hunter=getOniEntity();if(hunter==null)return;if(hunter instanceof Player p)msg(p,"&4作業失敗の大きな音！ &c"+directionFrom(p.getLocation(),heart));hunter.getWorld().playSound(hunter.getLocation(),Sound.ENTITY_GENERIC_EXPLODE,0.8f,0.7f);}
    private String directionFrom(Location from,Location to){double dx=to.getX()-from.getX(),dz=to.getZ()-from.getZ();String ns=Math.abs(dz)<2?"":(dz<0?"北":"南"),ew=Math.abs(dx)<2?"":(dx>0?"東":"西");String result=ns+ew;return result.isEmpty()?"すぐ近く":result+"方向";}
    private void startFinalPhaseBgm(){if(finalPhase||!getConfig().getBoolean("final-phase-bgm.enabled",true))return;finalPhase=true;activeBgmSound=getConfig().getString("final-phase-bgm.sound","onigame:final_phase");playFinalPhaseBgmToAll();long replay=Math.max(0,getConfig().getLong("final-phase-bgm.replay-seconds",194));if(replay>0)bgmTicker=Bukkit.getScheduler().runTaskTimer(this,this::playFinalPhaseBgmToAll,replay*20L,replay*20L);}
    private void playFinalPhaseBgmToAll(){if(state!=GameState.RUNNING)return;for(UUID id:participants){Player p=Bukkit.getPlayer(id);if(p!=null)playConfiguredBgm(p);}}
    private void playConfiguredBgm(Player p){String sound=getConfig().getString("final-phase-bgm.sound","onigame:final_phase");float volume=(float)getConfig().getDouble("final-phase-bgm.volume",0.8),pitch=(float)getConfig().getDouble("final-phase-bgm.pitch",1.0);p.stopSound(sound,SoundCategory.RECORDS);p.playSound(p.getLocation(),sound,SoundCategory.RECORDS,volume,pitch);}
    private void stopFinalPhaseBgm(){if(bgmTicker!=null){bgmTicker.cancel();bgmTicker=null;}String sound=activeBgmSound!=null?activeBgmSound:getConfig().getString("final-phase-bgm.sound","onigame:final_phase");for(Player p:Bukkit.getOnlinePlayers())p.stopSound(sound,SoundCategory.RECORDS);activeBgmSound=null;}
    @EventHandler public void onEntityPlace(EntityPlaceEvent e){
        if(!(e.getEntity() instanceof ArmorStand stand)||e.getPlayer()==null)return;
        ItemStack held=e.getHand()==EquipmentSlot.HAND?e.getPlayer().getInventory().getItemInMainHand():e.getPlayer().getInventory().getItemInOffHand();
        if(!held.hasItemMeta())return;String action=held.getItemMeta().getPersistentDataContainer().get(actionKey,PersistentDataType.STRING);if(!"heart_marker".equals(action))return;
        configureMarker(stand);msg(e.getPlayer(),"心臓地点マーカーを設置しました。ゲーム開始時、この位置に心臓が生成されます。");
    }
    @EventHandler public void onInventoryClick(InventoryClickEvent e){
        if(e.getInventory().getHolder() instanceof MenuHolder holder){e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p)||e.getCurrentItem()==null||!e.getCurrentItem().hasItemMeta())return;String action=e.getCurrentItem().getItemMeta().getPersistentDataContainer().get(actionKey,PersistentDataType.STRING);if(action==null)return;if(holder.type.equals("skills")&&action.startsWith("menu_skill:")){PlayerSkill skill=PlayerSkill.valueOf(action.substring("menu_skill:".length()));selectedSkill.put(p.getUniqueId(),skill);p.closeInventory();msg(p,"スキルを &b"+skill.display+" &fに設定しました。");}else if(holder.type.equals("oni")&&action.startsWith("menu_oni:")&&p.hasPermission("onigame.admin")){selectedOniType=OniType.valueOf(action.substring("menu_oni:".length()));p.closeInventory();msg(p,"次の鬼を &c"+selectedOniType.display+" &fに設定しました。");}return;}
        if(state!=GameState.RUNNING||oni==null||!e.getWhoClicked().getUniqueId().equals(oni))return;if(e.getSlotType()==InventoryType.SlotType.ARMOR||isDakkoArmor(e.getCurrentItem())||isDakkoArmor(e.getCursor()))e.setCancelled(true);
    }
    @EventHandler public void onDrop(PlayerDropItemEvent e){if(state==GameState.RUNNING&&e.getPlayer().getUniqueId().equals(oni)&&isDakkoArmor(e.getItemDrop().getItemStack()))e.setCancelled(true);}
    private void weakenOni(){LivingEntity entity=getOniEntity();if(entity==null)return;double max=Math.max(30,60-(brokenHearts*6));entity.getAttribute(Attribute.GENERIC_MAX_HEALTH).setBaseValue(max);if(entity.getHealth()>max)entity.setHealth(max);entity.addPotionEffect(new PotionEffect(PotionEffectType.WEAKNESS,120,Math.min(3,brokenHearts-1),false,true));if(brokenHearts==3&&entity instanceof Player p){p.getInventory().setItem(2,null);msg(p,"心臓の喪失により固有能力の一つが封印されました。");}}

    @EventHandler public void onInteract(PlayerInteractEvent e){
        if(state!=GameState.RUNNING)return;
        if(e.getClickedBlock()!=null&&heartHp.containsKey(LocationStore.encode(e.getClickedBlock().getLocation()))){e.setCancelled(true);if(e.getAction().isRightClick()&&e.getHand()==EquipmentSlot.HAND)toggleHeartRepair(e.getPlayer(),e.getClickedBlock());return;}
        if(e.getItem()==null||!e.getAction().isRightClick()||!e.getItem().hasItemMeta())return;String action=e.getItem().getItemMeta().getPersistentDataContainer().get(actionKey,PersistentDataType.STRING);if(action==null)return;e.setCancelled(true);Player p=e.getPlayer();if(action.startsWith("skill:")){if(!players.contains(p.getUniqueId()))return;usePlayerSkill(p,PlayerSkill.valueOf(action.substring(6)));}else if(oni!=null&&p.getUniqueId().equals(oni))useOniSkill(p,action);else if(action.equals("tracker"))trackHeart(p);
    }
    @EventHandler public void onSneak(PlayerToggleSneakEvent e){if(state==GameState.RUNNING&&e.isSneaking()&&repairingHeart.containsKey(e.getPlayer().getUniqueId())&&skillChecks.containsKey(e.getPlayer().getUniqueId()))resolveSkillCheck(e.getPlayer());}
    private boolean ready(Player p,String id,int cd){String k=p.getUniqueId()+":"+id;long now=System.currentTimeMillis();long until=cooldowns.getOrDefault(k,0L);if(until>now){msg(p,"あと &e"+((until-now+999)/1000)+"秒 &f待ってください。");return false;}cooldowns.put(k,now+cd*1000L);return true;}
    private void usePlayerSkill(Player p,PlayerSkill s){if(!ready(p,s.name(),s.cooldown))return;switch(s){case SPRINT->p.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,100,2,false,true));case INVISIBLE->p.addPotionEffect(new PotionEffect(PotionEffectType.INVISIBILITY,120,0,false,true));case SMOKE->{p.getWorld().spawnParticle(Particle.CAMPFIRE_COSY_SMOKE,p.getLocation(),160,4,2,4,.03);LivingEntity o=getOniEntity();if(o!=null&&o.getWorld().equals(p.getWorld())&&o.getLocation().distanceSquared(p.getLocation())<64)o.addPotionEffect(new PotionEffect(PotionEffectType.BLINDNESS,80,0,false,true));}case ONI_STRIKE->{LivingEntity o=getOniEntity();if(o!=null&&o.getWorld().equals(p.getWorld())&&o.getLocation().distanceSquared(p.getLocation())<=25){double damage=brokenHearts==totalHearts?12:3;o.damage(damage,p);o.setVelocity(o.getLocation().toVector().subtract(p.getLocation().toVector()).normalize().multiply(1.5).setY(.5));}else msg(p,"鬼が5ブロック以内にいません。");}}}
    private void useOniSkill(Player p,String action){int heartPenalty=brokenHearts*3;switch(action){case "dakko_tp"->{if(!ready(p,action,20+heartPenalty))return;Block b=p.getTargetBlockExact(Math.max(6,20-brokenHearts*3));if(b!=null)p.teleport(b.getLocation().add(.5,1,.5).setDirection(p.getLocation().getDirection()));}case "dakko_clone"->{if(brokenHearts>=3||!ready(p,action,35+heartPenalty))return;for(int n=0;n<Math.max(1,3-brokenHearts/2);n++){Fox f=p.getWorld().spawn(p.getLocation(),Fox.class);f.setCustomName(cc("&c"+p.getName()));f.setCustomNameVisible(true);f.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,200,1));Bukkit.getScheduler().runTaskLater(this,f::remove,200);}}case "kishin_charge"->{if(!ready(p,action,18+heartPenalty))return;p.setVelocity(p.getLocation().getDirection().normalize().multiply(Math.max(1.4,2.6-brokenHearts*.2)).setY(.15));p.getWorld().playSound(p.getLocation(),Sound.ENTITY_RAVAGER_ROAR,1,1);}case "kishin_slam"->{if(brokenHearts>=3||!ready(p,action,30+heartPenalty))return;p.getWorld().spawnParticle(Particle.EXPLOSION_LARGE,p.getLocation(),4);for(UUID id:players){Player q=Bukkit.getPlayer(id);if(q!=null&&!dead.contains(id)&&q.getWorld().equals(p.getWorld())&&q.getLocation().distanceSquared(p.getLocation())<49){q.damage(6,p);q.setVelocity(q.getLocation().toVector().subtract(p.getLocation().toVector()).normalize().multiply(1.2).setY(.8));q.addPotionEffect(new PotionEffect(PotionEffectType.SLOW,60,1));}}}}}
    private void trackHeart(Player p){Location nearest=heartHp.keySet().stream().map(LocationStore::decode).filter(Objects::nonNull).min(Comparator.comparingDouble(l->l.distanceSquared(p.getLocation()))).orElse(null);if(nearest==null){msg(p,"残っている心臓はありません。");return;}p.setCompassTarget(nearest);msg(p,"最寄りの心臓まで約 &e"+(int)nearest.distance(p.getLocation())+"m");}

    @EventHandler public void onDamage(EntityDamageByEntityEvent e){if(state!=GameState.RUNNING)return;Entity rawAttacker=e.getDamager() instanceof Projectile pr&&pr.getShooter() instanceof Entity shooter?shooter:e.getDamager();boolean attackerIsBot=oniBot!=null&&rawAttacker.getUniqueId().equals(oniBot);boolean attackerIsOni=(oni!=null&&rawAttacker.getUniqueId().equals(oni))||attackerIsBot;boolean victimIsOni=(oni!=null&&e.getEntity().getUniqueId().equals(oni))||(oniBot!=null&&e.getEntity().getUniqueId().equals(oniBot));if(e.getEntity() instanceof Player victim){boolean victimIsPlayer=players.contains(victim.getUniqueId());if((attackerIsOni&&victimIsOni)||(!attackerIsOni&&victimIsPlayer&&rawAttacker instanceof Player)&&!getConfig().getBoolean("friendly-fire",false)){e.setCancelled(true);return;}if(attackerIsBot)e.setDamage(getConfig().getDouble("bot.attack-damage",7.0));if(attackerIsOni&&repairingHeart.containsKey(victim.getUniqueId()))stopRepair(victim,"&c攻撃を受け、心臓への干渉が中断された。");}if(victimIsOni&&rawAttacker instanceof Player attacker&&!players.contains(attacker.getUniqueId()))e.setCancelled(true);}
    @EventHandler public void onAnyDamage(EntityDamageEvent e){if(state!=GameState.RUNNING||brokenHearts>=totalHearts)return;boolean protectedOni=(oni!=null&&e.getEntity().getUniqueId().equals(oni))||(oniBot!=null&&e.getEntity().getUniqueId().equals(oniBot));if(protectedOni)e.setDamage(e.getDamage()*Math.max(0,Math.min(1,getConfig().getDouble("oni-heart-protection.damage-taken-multiplier",0.25))));}
    @EventHandler public void onFoodChange(FoodLevelChangeEvent e){if(state==GameState.RUNNING&&e.getEntity() instanceof Player p&&participants.contains(p.getUniqueId()))e.setCancelled(true);}
    @EventHandler public void onCombust(EntityCombustEvent e){if(state==GameState.RUNNING&&((oniBot!=null&&e.getEntity().getUniqueId().equals(oniBot))||playerBots.contains(e.getEntity().getUniqueId())))e.setCancelled(true);}
    @EventHandler public void onEntityDeath(EntityDeathEvent e){if(state!=GameState.RUNNING)return;UUID id=e.getEntity().getUniqueId();if(oniBot!=null&&id.equals(oniBot)){e.getDrops().clear();e.setDroppedExp(0);oniBot=null;end(false,"&c鬼 討 滅――ぷれいやーの勝利");return;}if(playerBots.contains(id)){e.getDrops().clear();e.setDroppedExp(0);deadPlayerBots.add(id);clearPlayerBotWork(id);all("&7ぷれいやーBot は鬼に喰われた……");checkPlayerOutcome();}}
    @EventHandler public void onDeath(PlayerDeathEvent e){if(state!=GameState.RUNNING||!participants.contains(e.getPlayer().getUniqueId()))return;e.getDrops().clear();e.setDeathMessage(null);Bukkit.getScheduler().runTask(this,()->{Player p=e.getPlayer();p.spigot().respawn();p.setGameMode(GameMode.SPECTATOR);if(p.getUniqueId().equals(oni))end(false,"&c鬼 討 滅――ぷれいやーの勝利");else{dead.add(p.getUniqueId());all("&7"+p.getName()+" は鬼に喰われた……");checkPlayerOutcome();}});}
    @EventHandler public void onQuit(PlayerQuitEvent e){if(state!=GameState.RUNNING)return;UUID id=e.getPlayer().getUniqueId();if(id.equals(oni))end(false,"鬼が退出したため、ぷれいやーの勝利");else if(players.contains(id)){dead.add(id);checkPlayerOutcome();}}

    @Override public List<String> onTabComplete(CommandSender s,Command c,String l,String[] a){if(a.length==1)return List.of("join","leave","skills","skill","gmbook","onimenu","heartmode","marker","markers","bgm","bgmtest","bgmstop","botgame","onibotgame","testbook","testdestroy","set","heart","start","stop","status");if(a.length==2&&a[0].equalsIgnoreCase("skill"))return List.of("sprint","invisible","smoke","strike");if(a.length==2&&a[0].equalsIgnoreCase("heartmode"))return List.of("random","manual");if(a.length==2&&a[0].equalsIgnoreCase("bgm"))return List.of("onigame:final_phase","off");if(a.length==2&&a[0].equalsIgnoreCase("set"))return List.of("lobby","player","oni","exit");if(a.length==2&&(a[0].equalsIgnoreCase("start")||a[0].equalsIgnoreCase("botgame")||a[0].equalsIgnoreCase("onibotgame")))return List.of("dakko","kishin");if(a.length==3&&a[0].equalsIgnoreCase("onibotgame"))return List.of("1","2","3","4","5","6","7","8");return List.of();}
}
